apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sales-api
  name: sales-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-api
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      containers:
      - image: service-amd64:1.0
        name: service-amd64
        # limit resource to 100m for sales-api container
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m

