apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30778
