kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-2
# One control plane node and three "workers".
#
# While these will not add more real compute capacity and
# have limited isolation, this can be useful for testing
# rolling updates etc.
#
# The API-server and other control plane components will be
# on the control-plane node.
#
# You probably don't need this unless you are testing Kubernetes itself.
nodes:
- role: control-plane
  image: kindest/node:v1.23.17
  extraPortMappings:
  - containerPort: 30778
    hostPort: 30778
    listenAddress: "0.0.0.0"
    protocol: tcp
  extraMounts:
    - hostPath: /mnt/KIND
      containerPath: /storage  
